<?php

/**
 * @file
 * Defines an example shipping method for testing and development.
 */


/**
 * Implements hook_commerce_shipping_method_info().
 */
function pickup_commerce_shipping_method_info() {
    $shipping_methods = array();

    $shipping_methods['pickup_shipping_method'] = array(
        'title' => t('Pickup shipping method'),
        'description' => t('Defines shipping method by pickup.'),
    );

    return $shipping_methods;
}

/**
 * Implements hook_commerce_shipping_service_info().
 */
function pickup_commerce_shipping_service_info() {
  $shipping_services = array();

  $shipping_services['pickup_shipping_service'] = array(
    'title' => t('Pickup shipping service'),
    'display_title' => t('Pickup'),
    'shipping_method' => 'pickup_shipping_method',
    'price_component' => 'shipping',
    'weight' => 15,
    'callbacks' => array(
      'rate' => 'pickup_service_rate_order',
      'details_form' => 'pickup_service_details_form',
      'details_form_validate' => 'pickup_service_details_form_validate',
      'details_form_submit' => 'pickup_service_details_form_submit',
    ),
  );

  return $shipping_services;
}

/**
 * Shipping service callback: returns a base price array for a shipping service
 * calculated for the given order.
 */
function pickup_service_rate_order($shipping_service, $order)
{
  $rate = array(
    'amount' => 0,
    'currency_code' => 'RUB',
    'data' => [],
  );

  if (arg(0) != 'checkout') {
    // оставить самовывоз только для служесного пользования
    if (user_has_role(PRODUCT_MANAGER_RID) && $GLOBALS['user']->uid != 393) {
      return $rate;
    }
  }

  return false;
}


/**
 * Allows modules to alter the options array generated to select a shipping
 * service on the checkout form.
 */
function pickup_commerce_shipping_service_rate_options_alter(&$options, $order){
    if (isset( $order->shipping_rates['pickup_shipping_service'] )) {
        $options['pickup_shipping_service'] =   '<div class="carrier">' . t('Pickup') . '</div>' .
            '<div class="message">' . t('From our warehouse') . '</div>' .
            '<div class="cost">' . t('free', [], ['context' => 'Checkout delivery cost']) . '</div>';
    }
}

/**
 * Shipping service callback: returns the shipping service details form.
 */
function pickup_service_details_form($pane_form, $pane_values, $checkout_pane, $order, $shipping_service)
{
    // вывести инфо о пункте самовывоза
    $pane_form = array();

    $pane_form['info'] = array(
        '#markup' => '<div class="form-item form-item-markup"><p>Забрать товар можно по адресу г. Кирово-Чепецк, ул. Производственная, д.6</p><p></p></div>',
    );

  $user_info = ext_user_get_user_info($order->uid, true);
    $pane_form['username'] = array(
        '#title' => 'Фамилия, Имя, Отчество',
        '#type' => 'textfield',
        '#default_value' => empty($user_info['name']['fullname']) ? '' : $user_info['name']['fullname'],
    );
    $pane_form['phone'] = array(
        '#title' => 'Телефон',
        '#type' => 'textfield',
        '#attributes' => ['class' => ['masked-phone']],
        '#default_value' => empty($user_info['phone']) ? '' : $user_info['phone'],
    );

    $pane_form['notes'] = array(
        '#title' => t('Notes to order'),
        '#type' => 'textarea',
        '#rows' => 2,
    );

    $pane_form['callme'] = array(
        '#title' => t('Call me to get details about my order and delivery'),
        '#type' => 'checkbox',
        '#default_value' => empty($user_info['address']['callme']) ? '' : $user_info['address']['callme'],
    );

    return $pane_form;
}

/**
 * Shipping service callback: validates the example shipping service details.
 */
function pickup_service_details_form_validate($details_form, $details_values, $shipping_service, $order, $form_parents)
{
  $validate = true;

  $field = 'username';
  if (empty($details_values[$field])) {
    form_set_error(implode('][', array_merge($form_parents, [$field])), 'Заполните это поле');
    $validate = false;
  }
  if (drupal_strlen($details_values[$field]) < 5) {
    form_set_error(implode('][', array_merge($form_parents, [$field])), 'Поле заполнено некорректно');
    $validate = false;
  }
  $field = 'phone';
  if (!ext_user_valid_phone($details_values[$field])) {
    form_set_error(implode('][', array_merge($form_parents, [$field])), 'Укажите в формате 7 (xxx) xxx-xxxx');
    $validate = false;
  }

  return $validate;
}

/**
 * Shipping service callback: increases the shipping line item's unit price if
 * express delivery was selected.
 */
function pickup_service_details_form_submit($details_form, $details_values, $line_item)
{
    // сохраняем введенные пользователем данные
    $order_wrapper = entity_metadata_wrapper('commerce_order', $line_item->order_id);

    $order_wrapper->field_username = $details_values['username'];
    $order_wrapper->field_phone = $details_values['phone'];
    $order_wrapper->commerce_customer_shipping->field_notes = $details_values['notes'];
    $order_wrapper->commerce_customer_shipping->field_callme = $details_values['callme'];
    $order_wrapper->commerce_customer_shipping->save();
    $order_wrapper->save();
}

// callback функция, возвращающая информацию о доставке для заказов
function pickup_shipping_service_info($item)
{
    $component_data = empty($item->commerce_total['und'][0]['data']) ? [] : $item->commerce_total['und'][0]['data'];
    return [
        'title' => $item->line_item_label,
        'method' => $item->commerce_shipping_service,
        'address' => '613048, Кирово-Чепецк, ул. Производственная, д.6',
    ];
}
