<?php

/**
 * Implements hook_menu().
 */
function ext_product_menu() {
  $items['api/product/%/set-in-stock'] = array (
    'page callback' => 'ext_product_product_status_update',
    'page arguments' => array(2, 3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['api/product/%/set-out-of-stock'] = array (
    'page callback' => 'ext_product_product_status_update',
    'page arguments' => array(2, 3),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/joy/api'] = array(
    'title' => 'API сайта',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_product_api_settings'),
    'access arguments' => array('access manager settings'),
    'file' => 'includes/ext_product.admin.inc',
  );


  return $items;
}

/**
 * menu callback
 */
function ext_product_product_status_update($pid = null, $op = null) {
  // проверить Токен
  $message = "Bad query";
  if ($_GET['api_key'] == variable_get('api_key') && is_numeric($pid) && $op) {
    // изменить статус товара
    $product_wr = entity_metadata_wrapper('commerce_product', $pid);
    if ($product_wr->value()) {
      switch ($op) {
        case 'set-in-stock':
          $stock = 0;
          break;

        case 'set-out-of-stock':
          $stock = 1;
          break;
      }

      if (isset($stock)) {
        db_update('field_data_field_p_out_of_stock')
          ->fields(['field_p_out_of_stock_value' => $stock])
          ->condition('bundle', 'product')
          ->condition('entity_id', $pid)
          ->execute();
        $message = "OK";
      }
    }
  }

  drupal_json_output($message);
}
