<?php

/**
 * Implements hook_menu().
 */
function ext_product_menu() {
  $items['api/product/set'] = array (
    'page callback' => 'ext_product_product_update',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/joy/api'] = array(
    'title' => 'API сайта',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ext_product_api_settings'),
    'access arguments' => array('access manager settings'),
    'file' => 'includes/ext_product.admin.inc',
  );


  return $items;
}

/**
 * menu callback
 */
function ext_product_product_update() {
  // проверить Токен
  $message = "Bad query";

  if ($_GET['api_key'] == variable_get('api_key') && isset($_GET['stock']) && in_array($_GET['stock'], [0, 1]) && isset($_GET['pid'])) {
    // изменить статус товара
    $stock = $_GET['stock'];
    $pid = $_GET['pid'];
    $product_wr = entity_metadata_wrapper('commerce_product', $pid);
    if ($product_wr->value()) {
        $product_wr->field_p_out_of_stock->set(!$stock);
        $product_wr->save();
        $message = "OK";
    }
  }

  drupal_json_output($message);
}
