<?php

/**
 * Implements hook_page_build().
 */
function add_marketing_page_build(&$page)
{
  // добавить Пользователю маркетинговую информацию о UTM из кукис
  global $user;
  if ($user->uid && !empty($_COOKIE['user_marketing'])) {
    $marketing_server = [];
    if (!empty($user->data['marketing'])) {
      $marketing_server = $user->data['marketing'];
    }
    $marketing_browser = json_decode($_COOKIE['user_marketing'], true);
    $marketing_server_old = $marketing_server;
    $marketing_server = array_replace_recursive($marketing_server, $marketing_browser);
    $user->data['marketing'] = $marketing_server;
    if ($marketing_server_old != $marketing_server) {
      user_save($user);
    }
  }
}

/**
 * Implements hook_views_api().
 */
function add_marketing_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'add_marketing') . '/views',
  );
}

/**
 * Implements hook_views_data_alter().
 */
function add_marketing_views_data_alter(&$data)
{
  $data['users']['marketing'] = array(
    'field' => array(
      'title' => t('Marketing'),
      'help' => t('View gathered marketing info.'),
      'handler' => 'add_marketing_handler_field_marketing',
    ),
    'filter' => array(
      'title' => t('Marketing'),
      'help' => t('Filter by marketing info.'),
      'handler' => 'add_marketing_handler_filter_marketing',
    ),
  );
}


/**
 * Implements hook_commerce_order_presave()
 */
function add_marketing_commerce_order_presave($order)
{
  if (empty($order->original)) return;

  // при удачной оплате Cбером отправить событие Purchase
  if ($order->original->status != 'paid' && $order->status == 'paid'
      && isset($order->data['payment_method']) && $order->data['payment_method'] == 'commerce_rbspayment_custom|commerce_payment_commerce_rbspayment_custom') {

    if (!user_has_role(PRODUCT_MANAGER_ROLE_ID, $GLOBALS['user'])) {
      $order_wr = entity_metadata_wrapper('commerce_order', $order);
      fbq('Purchase', ['total' => $order_wr->commerce_order_total->amount->value()/100]);
    }
  }
}

/*
 * ---------------------------- Facebook ---------------------------------------
 */

/**
 * вызов API трекинга событий facebook
 */
function fbq($event, $data = [])
{
  // токен из ЛК ФБ
  $pixel_id = '2267509073307955';
  $access_token = 'EAADZChLq0MxgBAGCZBLIX6VdaeZCtXoOTH9gB35pLYpjWukawivmjtr7uwz0gZADiVVJQfjUkVF2S58OQwROKJhq8m1skDB43zGsWo89mP64DSM3KaxiiRs78GaATQoqZChdEWQJCXvnwkaCZCqSZAyg5dzbyr7UvpiSall6rWBEGnNB9iYaKZBccIgbJmOkM9kZD';

  $request = [
    'data' => [],
    'access_token' => $access_token,
  ];

  if (!empty($_COOKIE['_fbp'])) {
    $request['fbp'] = $_COOKIE['_fbp'];
  }
  if (!empty($_COOKIE['_fbc'])) {
    $request['fbc'] = $_COOKIE['_fbc'];
  }

  $event_array = [
    'event_name' => $event,
    'event_time' => REQUEST_TIME,
    "event_source_url" => $GLOBALS['base_url'] . '/' . $_GET['q'],
    'user_data' => [
      "client_ip_address" => $_SERVER['REMOTE_ADDR'],
      "client_user_agent" => $_SERVER['HTTP_USER_AGENT'],
//      'em' => hash('sha256', 'bla-bla-bla'),
//      'ph' => hash('sha256', 'bla-bla-bla'),
    ],
  ];

  switch ($event) {
    case 'InitiateCheckout':
      break;

    case 'Purchase':
      $event_array['custom_data'] = [
        'value' => $data['total'],
        'currency' => 'RUB',
      ];
      break;
  }
  $request['data'][] = $event_array;

  // для dev сервера только вывести в лог
  if (strpos($_SERVER['HTTP_HOST'], '.local') === false) {
    $ch = curl_init();
    curl_setopt_array($ch, [
      CURLOPT_URL => "https://graph.facebook.com/v7.0/$pixel_id/events",
      CURLOPT_POST => true,
      CURLOPT_POSTFIELDS => json_encode($request),
      CURLOPT_HTTPHEADER => [
        "Content-Type: application/json"
      ],
      CURLOPT_RETURNTRANSFER => true
    ]);

    if ($result = curl_exec($ch)) {
      watchdog('facebook', 'Отправка события FBQ.<br />Событие: !event.<br />Данные: !request<br />Ответ: !result', array('!event' => $event, '!request' => '<pre>' . print_r( $request, true) . '</pre>', '!result' => '<pre>' . print_r( $result, true) . '</pre>'), WATCHDOG_DEBUG);
      return json_decode($result, TRUE);
    } else return false;
  } else {
    //watchdog('facebook', 'Эмуляция отправки события FBQ.<br />Событие: !event.<br />Данные: !request', array('!event' => $event, '!request' => '<pre>' . print_r( $request, true) . '</pre>'), WATCHDOG_DEBUG);
    return true;
  }
}

/**
 * Implements hook_preprocess_page()
 */
function add_marketing_preprocess_page(&$vars)
{
//  if (strpos($_SERVER['HTTP_HOST'], '.local') === false) {
    drupal_add_js(drupal_get_path('module', 'add_marketing') . '/js/add_marketing.js');
//  }
}
