<?php

/**
 * @file
 * Hook implementations and API functions for the commerce_userpoints module.
 */

/**
 * Implements hook_help().
 */
function commerce_userpoints_custom_help($path) {
  $help = '';
  switch ($path) {
    case 'admin/commerce/config/currency/userpoints':
      $help = t('This page allows to set up a virtual currency for each !points category. After this, it can for example be used to buy products with these !points.', userpoints_translation());
      break;
  }
  return $help;
}
/**
 * Implements hook_permission().
 */
function commerce_userpoints_custom_permission() {
  return array(
    'admin commerce userpoints' => array(
      'title' => t('admin commerce userpoints'),
      'description' => t('admin commerce userpoints'),
    )
  );
}

/**
 * Implements hook_menu().
 */
function commerce_userpoints_custom_menu() {
  $items = array();

  $items['admin/commerce/config/currency/default'] = array(
    'title' => 'Currency settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/commerce/config/currency/userpoints'] = array(
    'title' => '!Points currencies',
    'title arguments' => userpoints_translation(),
    'page callback' => 'commerce_userpoints_custom_currencies_page',
    'access arguments' => array('configure store'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'commerce_userpoints_custom.admin.inc',
  );
  $items['admin/commerce/config/currency/userpoints/add'] = array(
    'title' => 'Add a !points currency',
    'title arguments' => userpoints_translation(),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_userpoints_custom_currencies_form'),
    'access arguments' => array('configure store'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'commerce_userpoints_custom.admin.inc',
  );
  $items['admin/commerce/config/currency/userpoints/edit/%commerce_userpoints'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_userpoints_custom_currencies_form', 6),
    'access arguments' => array('configure store'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'commerce_userpoints_custom.admin.inc',
  );
  $items['admin/commerce/config/currency/userpoints/delete/%commerce_userpoints'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_userpoints_custom_currencies_delete', 6),
    'access arguments' => array('configure store'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'commerce_userpoints_custom.admin.inc',
  );

  return $items;
}

/**
 * Returns the currently configured userpoints currencies.
 *
 * @return
 *   An array of userpoints categories
 */
function commerce_userpoints_custom_currencies() {
  return variable_get('commerce_userpoints_custom_currencies', array());
}
/**
 * @return
 *   An array of userpoints categories that used as currency.
 */
function commerce_userpoints_custom_currencies_option_list() {
  $userpoint_currencies = commerce_userpoints_custom_currencies();
  if (!empty($userpoint_currencies)) {
    $options = array();
    foreach ($userpoint_currencies as $key => $val) {
      $options[$key] = $val['name'];
    } 
    return $options;
  }
  return FALSE;
}

/**
 * Load a userpoints currency based on the code.
 */
function commerce_userpoints_custom_load($code) {
  $currencies = commerce_userpoints_custom_currencies();
  if (isset($currencies[$code])) {
    return $currencies[$code];
  }
  return FALSE;
}

/**
 * Implements hook_commerce_currency_info().
 */
function commerce_userpoints_custom_commerce_currency_info() {
  $currencies = array();
  $default_currency = commerce_default_currency();
  foreach (commerce_userpoints_custom_currencies() as $currency) {
    $currencies[$currency['code']] = array(
      'code' => $currency['code'],
      'symbol' => $currency['symbol'],
      'name' => $currency['name'],
      'rounding_step' => '1',
      // Userpoints currently does not support decimals.
      'decimals' => 0,
      'conversion_rate' => !empty($currency['conversion_rate']) ? $currency['conversion_rate'] : 0.01,
    );
  }
  return $currencies;
}

/**
 * Implements hook_form_alter().
 */
function commerce_userpoints_custom_form_userpoints_admin_txn_alter(&$form, &$form_state)
{
    // не показываем статус остальным, если он отключен
    $form['status']['#access'] = !isset($GLOBALS['user']->roles[3]) && (bool)variable_get(USERPOINTS_POINTS_MODERATION, 0);
}


/**
 * Implements hook_userpoints().
 */
function commerce_userpoints_custom_userpoints($op, &$points_params = array())
{
    // Transactions without points are not passed to rules for now.
    if ($op != 'points after' || !is_array($points_params) || !isset($points_params['points'])) {
        return;
    }

    // отправить уведомления пользователям
    $event = 'points_add';
    $account = user_load($points_params['uid']);
    $params['account'] = $account;
    $params['userpoints'] = $points_params;

    // письмо Пользователю
//    drupal_mail('mailing', $event, 'mega_comp@mail.ru', user_preferred_language($account), $params);
    if (!empty($account->mail)) {
        drupal_mail('mailing', $event, $account->mail, user_preferred_language($account), $params);
    }

    // смс пользователю
    ext_user_sms_gate_sms($event, $params);
}


/**
 * Implements hook_theme().
 * cu_points is short of commerce_userpoints_custom_points.
 */
function commerce_userpoints_custom_theme() {
  return array(
    'cu_points' => array(
      'variables' => array($points = NULL),
    )
  );
}

function theme_cu_points($vars) {
  return '<span class="commerce_userpoints-points">' . $vars['points'] . '</span>';
}
